# Numpy 3

> argmin

> argmax

> argsort

> array generate br range

> Generate Diagonal array 

> generate array elements with fix difference

> Various random functions -  rand(), randn(), randf(), randint()

> additional operations on array - sqroot() , sin() & cos() , cumsum()

> Broadcasting in numpy

> COPY and VIEW

> Difference between copy and view

> Join array

> Stack attribute

> Split array

> searching in array

> sorting in array

@ Use of argmin

In [99]:
import numpy as np

In [100]:
arr=np.array([10,2,3,4])
index_of_minimum=arr.argmin()
print(index_of_minimum)

1


@ Use of argmax

In [101]:
arr=np.array([10,2,3,4])
index_of_maximum=arr.argmax()
print(index_of_maximum)

0


@ Use of argsort

In [102]:
index__sort=arr.argsort()
print(index__sort)

[1 2 3 0]


In [103]:
# Generate dimensiona as want

arr1=np.array([1,2,3,4],ndmin=10)
print(arr1)
print(arr1.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


#### generate array as want 

In [104]:
arr2=np.arange(3,9)  # by this the array will be created from 3 to 8 
arr2

array([3, 4, 5, 6, 7, 8])

#### Generate Diagonal array 

In [105]:
arr3=np.eye(3)  # 3*3 dimensional array is created using 'eye'
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
arr4=np.eye(4,7)
arr4

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

#### generate array elements with fix difference

In [107]:
arr_lin=np.linspace(0,20,num=8)
arr_lin

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

## Various random functions

1. rand() = This function is used to generate random vlaues between 0 and 1

In [108]:
var=np.random.rand()   # generate random value
print(var)

var2=np.random.rand(2,5)  # generate a array  of 2*3 with random values between 0-1  
print(var2)  

0.2226592783706064
[[0.64234688 0.60747293 0.32413822 0.72653636 0.2715    ]
 [0.2027201  0.41506867 0.89861721 0.86063204 0.53695481]]


2. randn() = This function is used to generate random vlaues closest to 0. May return +ve or -ve as well

In [109]:
var3=np.random.randn()  # generate random value
print(var3)

var4=np.random.randn(4,6)   #generate array
print(var4)    

1.2290869247403715
[[-0.28743706 -1.56082372 -0.95363285  0.78298109 -0.2378703   0.3774634 ]
 [-2.20908408  0.23544794  0.67589899  0.87965212 -2.30591087  1.59444663]
 [ 0.50585666  0.67135258  0.65810602  1.3928001   0.314703   -0.23325492]
 [ 1.06001312  0.73399892 -0.06844504  0.59889168 -0.34502826  1.11833283]]


3. ranf() = it returns 1D array with specific shape filled with floats between range [0.0,1.0)

In [110]:
var5=np.random.ranf(4)
var5

array([0.04261696, 0.33812899, 0.11396558, 0.38625973])

4. Randint() = It generate a array filled with elements between given range

In [111]:
var6=np.random.randint(1,90)  #  returns a single element between range 1-90
print(var6)

var7=np.random.randint(1,50,20) # returns a array of 20 element between range 1-90
print(var7)

79
[32 49 25 48 43 46 19 43 43  3 21 41 23 49 14 13 12 29 43  2]


## Some additional operations on array

1. sqroot
2. sin and cos
3. cumsum

1. sqroot

In [112]:
arr1=[1,2,3,4,5,6]
sqr=np.sqrt(arr1)    # sqrt used to retuen square root of every element
sqr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

2. sin and cos

In [113]:
print(np.sin(arr1))   # done sin function on every element of arr1 array
print(np.cos(arr1))   # done cos function on every element of arr1 array

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]


3. cumsum

In [114]:
print(np.cumsum(arr1))  # returns the cumulative sum of the elements . like if arr1=[1,2,3,4,5,6] then 1,1+2=3,3+3=6,6+4=10,10+5=15,15+6=21

[ 1  3  6 10 15 21]


## Broadcasting in numpy

>For 1D array

* addition of two 1D arrays

In [115]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6])

print(arr1+arr2)          # so to add two 1D arrays , dimension(shape) of both must be same otherwise it will give ValueError

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

>For 2D array

* for two 2d array in first shape is (m * _ ) and second  is ( _ * m)

In [ ]:
var1=np.array([1,2,3,4,8])          # var1 shape is 1*_ ( 1 row and 4 column )
var2=np.array([[1],[5],[7],[9],[8]])  # var2 sahpe is _*1 ( 4 row and 1 column )
print(var1)
print()
print(var2)
print()
print(var1+var2)     # (1*4) and (4*1) result will be 4*4
print()
print(var1*var2)

[1 2 3 4 8]

[[1]
 [5]
 [7]
 [9]
 [8]]

[[ 2  3  4  5  9]
 [ 6  7  8  9 13]
 [ 8  9 10 11 15]
 [10 11 12 13 17]
 [ 9 10 11 12 16]]

[[ 1  2  3  4  8]
 [ 5 10 15 20 40]
 [ 7 14 21 28 56]
 [ 9 18 27 36 72]
 [ 8 16 24 32 64]]


# COPY AND VIEW

#### 1. Copy

Copy function is used to copy the existing array 

In [ ]:
e_arr=np.array([1,2,3,4])
copy_arr= np.copy(e_arr)

print("Real: ",e_arr)
print("Copy: ",e_arr)

Real:  [1 2 3 4]
Copy:  [1 2 3 4]


#### 2. View

view shows the array allocated to it

In [ ]:
e_arr=np.array([10,20,34,48])
view_arr= e_arr.view()

print("Real: ",e_arr)
print("View: ",e_arr)

Real:  [10 20 34 48]
View:  [10 20 34 48]


### DIfference between Copy and View

copy- copy owned data from real.

real- real dosen't have it's own data.



copy-copy of a array is new array.

view- a view of original data.


copy- changes in copy array dosen't reflect in original array.

view- changes in view array will reflect in original array.

# * Join Array

* In this cell we will read about joining of arrays

>1d array

In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7])

j_arr=np.concatenate((arr1,arr2))
print(j_arr)

[1 2 3 4 5 6 7]


>2D array

In [ ]:
arr1=np.array([[1,2,3,4],[2,7,9,9]])
arr2=np.array([[5,6,7,5],[2,5,6,0]])

new_arr=np.concatenate((arr1,arr2),axis=1)  # axis =1 -> arrays wiil be join accoring to column
print(arr1)
print()
print(arr2)
print()
print(new_arr)

[[1 2 3 4]
 [2 7 9 9]]

[[5 6 7 5]
 [2 5 6 0]]

[[1 2 3 4 5 6 7 5]
 [2 7 9 9 2 5 6 0]]


In [ ]:
arr1=np.array([[1,2,3,4],[1,3,5]])  #  To avoid ValueError , setting an array element with a sequence.
arr2=np.array([[5,6,7],[1,2,4,5]])

j_arr=np.concatenate((arr1,arr2))
print(j_arr)         # this join won't work

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## Stack

* stack besed on join opeartion but retuen pairs in the a array

In [ ]:
arr_1=np.array([1,2,3,4])
arr_2=np.array([5,6,7,8])

new_a=np.stack((arr_1,arr_2),axis=1)
new_a_0=np.stack((arr_1,arr_2),axis=0)   # by default axis always is 0
new_a_d=np.stack((arr_1,arr_2))
print(new_a)
print()
print(new_a_0)
print()
print(new_a_d)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]


## Split array

* arrays can be split in equal parts by split function

In [ ]:
n_arr=np.array([1,2,3,4,5,6])

n_new=np.split(n_arr,3)   # split the array in 3 parts
# n_new1=np.split(n_arr,4)   # split the array in 4 parts
# n_new2=np.split(n_arr,5)   # split the array in 5 parts
n_new3=np.split(n_arr,2)   # split the array in 2 parts

print(n_new)
print()
# print(n_new1) 
# print()
# print(n_new2) 
print()
print(n_new3) 

# split in 4 and 5 parts can not be possiple. spliting should equal(each part contain equal elements)

[array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2, 3]), array([4, 5, 6])]


## Searching in numpy


In [ ]:
a1=np.array([1,2,4,6,2,8,9])
x=np.where(a1==2)       # we can search an element in an array and can get its index using index
print(x)

(array([1, 4]),)


In [ ]:
a1=np.array([1,2,4,6,2,8,9])
x=np.where(a1%2==0)       
print(x)

(array([1, 2, 3, 4, 5]),)


### Search sorted Array 

it retrun the index where the specific value would be inserted in sorted array

In [ ]:
a2=np.array([1,2,4,6,7,9])
x1=np.searchsorted(a2,5) # it shows in a1 what will be the location of 5 ( sorted array)      
x2=np.searchsorted(a2,3) # it shows in a1 what will be the location of 3 ( sorted array)

print(x1)
print(x2)

3
2


## SORT

In [ ]:
a1=np.array([2,4,7,1,45,65,1,24,7])
print(np.sort(a1))

[ 1  1  2  4  7  7 24 45 65]


In [ ]:
a2=np.array(['a','f','g','r'])
print(np.sort(a2))

['a' 'f' 'g' 'r']
