# Numpy 2


> 2D Array

> 3D Array

> Accessing Elements in every type of array

> Conversion 3D TO 1D

2D ARRAY

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

2

In [5]:
arr.shape

(3, 3)

In [6]:
print(arr[1,2])
print(arr[-2,-2])

6
5


In [7]:
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
print(arr+2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
print(arr[0:2])

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr [0:2,0:2])

[[1 2]
 [4 5]]


In [11]:
print(arr[0:2,1:])

[[2 3]
 [5 6]]


In [12]:
print(arr[1:,:2])

[[4 5]
 [7 8]]


In [13]:
print(arr[-2:,-3:])

[[4 5 6]
 [7 8 9]]


In [14]:
arr[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
print(arr[:,1:])

[[2 3]
 [5 6]
 [8 9]]


SOME FUNCTIONS

In [16]:
print(np.ones(10)) #to generate quick array
print(np.zeros(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
np.linspace(1,50,10) # 1 to 50 , 10 item ( uniform distribution )

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

3D ARRAY

3D array have multiple two dimensional arrays(Matrix)

In [18]:
arr3=np.array([[[1,2,3,4],[1,3,4,5],[1,2,3,4]],[[1,2,3,4],[3,5,6,7],[5,6,7,8]],[[0,9,8,7],[9,8,7,6],[7,6,5,4]]])

In [19]:
arr3.ndim

3

In [20]:
arr3

array([[[1, 2, 3, 4],
        [1, 3, 4, 5],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [3, 5, 6, 7],
        [5, 6, 7, 8]],

       [[0, 9, 8, 7],
        [9, 8, 7, 6],
        [7, 6, 5, 4]]])

In [21]:
arr3.shape   # 3= table , 3 rows, 4 columns

(3, 3, 4)

In [22]:
arr3[1]  #access 1st table

array([[1, 2, 3, 4],
       [3, 5, 6, 7],
       [5, 6, 7, 8]])

In [23]:
arr3[0:2] # access table 1 and 2

array([[[1, 2, 3, 4],
        [1, 3, 4, 5],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [3, 5, 6, 7],
        [5, 6, 7, 8]]])

In [24]:
arr3[0:3:2] #access table 1st and 3rd

array([[[1, 2, 3, 4],
        [1, 3, 4, 5],
        [1, 2, 3, 4]],

       [[0, 9, 8, 7],
        [9, 8, 7, 6],
        [7, 6, 5, 4]]])

In [25]:
arr3[1,:2] #access 1st table 2 rows

array([[1, 2, 3, 4],
       [3, 5, 6, 7]])

In [26]:
arr3[0:4,0,:] #access ever table's first row

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [0, 9, 8, 7]])

In [27]:
arr3[:,-3,:]


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [0, 9, 8, 7]])

In [28]:
arr3[2,1:,1:] #access 3rd tables small matrix

array([[8, 7, 6],
       [6, 5, 4]])

In [29]:
arr3[0,1:,1:] #acess with +ve index

array([[3, 4, 5],
       [2, 3, 4]])

In [30]:
arr3[-3,-2:,-3:] #acess with -ve index

array([[3, 4, 5],
       [2, 3, 4]])

In [31]:
arr3[:,1:,1:] #acess ever tables's last 2 rows and 3 columns

array([[[3, 4, 5],
        [2, 3, 4]],

       [[5, 6, 7],
        [6, 7, 8]],

       [[8, 7, 6],
        [6, 5, 4]]])

In [32]:
arr3[:,-2:,-3:] # with -ve index

array([[[3, 4, 5],
        [2, 3, 4]],

       [[5, 6, 7],
        [6, 7, 8]],

       [[8, 7, 6],
        [6, 5, 4]]])

In [33]:
arr3[:,-1,::-1]  # access every tables's last row in reverse order

array([[4, 3, 2, 1],
       [8, 7, 6, 5],
       [4, 5, 6, 7]])

Convert 3D array in 1D array 

By ravel() function .

In [34]:
arr3.ravel()

array([1, 2, 3, 4, 1, 3, 4, 5, 1, 2, 3, 4, 1, 2, 3, 4, 3, 5, 6, 7, 5, 6,
       7, 8, 0, 9, 8, 7, 9, 8, 7, 6, 7, 6, 5, 4])

By flatten ()

In [35]:
arr3.flatten()

array([1, 2, 3, 4, 1, 3, 4, 5, 1, 2, 3, 4, 1, 2, 3, 4, 3, 5, 6, 7, 5, 6,
       7, 8, 0, 9, 8, 7, 9, 8, 7, 6, 7, 6, 5, 4])

By resahpe( )

In [36]:
arr3.reshape(36) #(3,3,4)=39

array([1, 2, 3, 4, 1, 3, 4, 5, 1, 2, 3, 4, 1, 2, 3, 4, 3, 5, 6, 7, 5, 6,
       7, 8, 0, 9, 8, 7, 9, 8, 7, 6, 7, 6, 5, 4])