# NUMPY 1


> Importing Library numpy

> Check version of numpy 

> 1D Array

> Operations on 1D array

> Tasks to solve

In [1]:
import numpy as np
np.__version__     # numpy = numerical python

'2.0.1'

In [2]:
arr=np.array([25,10,20,30,40,50,60])

print(arr)

[25 10 20 30 40 50 60]


In [3]:
type(arr) #ndarray = n dimensional array

numpy.ndarray

In [4]:
arr.ndim   #function to check dimension 

1

In [5]:
arr.size # size elements of array len(arr)

7

In [6]:
arr.shape   #describe m*n

(7,)

In [7]:
arr.dtype # datatype of array

dtype('int64')

In [8]:
array=np.array([1,2,3,4,5,6.6])  #because of a single float variable all convert to float
array

array([1. , 2. , 3. , 4. , 5. , 6.6])

In [9]:
array.dtype

dtype('float64')

In [10]:
array1=np.array([1,2,3,4.5,"rahul"])  #because of a single string variable all convert to string
array1

array(['1', '2', '3', '4.5', 'rahul'], dtype='<U32')

In [11]:
array1.dtype

dtype('<U32')

In [12]:
arr[2]

np.int64(20)

In [13]:
print(arr[-3:])
print(arr[4::])
print(arr[-1:-4:-1]) # 1 shows +ve direction and -1 shows negative direction
print(arr[-3::1])

[40 50 60]
[40 50 60]
[60 50 40]
[40 50 60]


In [14]:
# addition
arr+5

array([30, 15, 25, 35, 45, 55, 65])

In [15]:
#subtraction
arr-5

array([20,  5, 15, 25, 35, 45, 55])

In [16]:
#divide
arr/5


array([ 5.,  2.,  4.,  6.,  8., 10., 12.])

In [17]:
max(arr)

np.int64(60)

In [18]:
min(arr)

np.int64(10)

In [19]:
np.mean(arr) # mean=avg

np.float64(33.57142857142857)

In [20]:
np.median(arr) # median = center number

np.float64(30.0)

In [21]:
np._Mode(arr)  # numpy has no mode attribute
#mode= frequency of data

AttributeError: module 'numpy' has no attribute '_Mode'

In [ ]:
np.random.randint(2,300,10) # means array of 10 items between 2-300

array([264, 209, 181, 294, 276,  17, 105,  60, 197,  95], dtype=int32)

In [ ]:
# to generate m*n array
np.random.rand(2,3)

array([[0.18929289, 0.62368485, 0.04484459],
       [0.92248238, 0.47979056, 0.64778753]])

In [ ]:
arr.dtype='int32'
arr.dtype  # that's way we can change datatype

dtype('int32')

In [ ]:
import random,string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
string.digits

'0123456789'

In [ ]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [ ]:
alpha= string.ascii_letters+string.digits
alpha

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

In [ ]:
alpha.split

<function str.split(sep=None, maxsplit=-1)>

In [ ]:

import numpy as np
arr1 =np.random.randint(1,4500,100)
print(arr1)


[ 953 4141 1144 2131 3512 3288   48 1411 4352 4062 1476 2094  567  490
   39 1746 1051 3192  803 3228 1578 3637 4283 3763  386 1488  222 4497
  726 2486  323  372 4013 2949 1995 2613 4353 3259   73  663 2748 4330
 3791  325 1375 2473  376 2635 1531  339 3659  503  535 4170 2174 3298
 1359 1470 2538 2441 2876  955 3815  265 3941 2715 2050 4459 2883   84
 1290 2204  847 3290   73 1986 2023 2978 3752  309 1124  279 1951 3309
  585 1309 1738 1328 2138 3063 4223 2746 4383 4434 1951 3496 2815 4280
 3157 1365]


TASKS 
1. Try to calculate no of items <= 100 ( try diff methods)
2. Try to calculate no of even no.


1. Try to calculate no of items <= 100 ( try diff methods)

In [ ]:
# 1. try to calculate no of items <= 100 ( try diff methods)

        # method 1 = Using loop 
count=0
for i in range(0,100):
    if arr1[i] <= 100:
        print(arr1[i],end=" ")
        count+=1
print("\nNo of elements less then 100 :->  ",count)

48 39 73 84 73 
No of elements less then 100 :->   5


In [ ]:
     # Methhod 2= Using sum attribute in array 

count=np.sum(arr1<=100)
print("No of elements less then 100 are :-> ",count)  

No of elements less then 100 are :->  5


In [ ]:
    # Method 3 = using count_nonzero attribute
count=np.count_nonzero(arr1<=100)
print(count)  

5


2. Try to calculate no of even no.

In [ ]:
# Method 1 = Using loop

count=0
for i in range(0,100):
    if arr1[i]%2==0:
        print(arr1[i],end=" ")
        count+=1
print("\nEven numbers present in random array:->  ",count)

1144 3512 3288 48 4352 4062 1476 2094 490 1746 3192 3228 1578 386 1488 222 726 2486 372 2748 4330 376 4170 2174 3298 1470 2538 2876 2050 84 1290 2204 3290 1986 2978 3752 1124 1738 1328 2138 2746 4434 3496 4280 
Even numbers present in random array:->   44


In [ ]:
# Method 2= using sum attribute
count=np.sum(arr1%2==0)
print("even numbers are :> ",count)

even numbers are :>  44


In [ ]:
#     Method 3 = using count_nonzero attribute
count=np.count_nonzero(arr1%2==0)
print(count) 

44
